definitions:
  handlers.AddToCartRequest:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    type: object
  handlers.ConfirmRequest:
    properties:
      code:
        example: "123456"
        type: string
      phone:
        example: "+79991234567"
        type: string
    type: object
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handlers.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  handlers.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  handlers.StartRequest:
    properties:
      phone:
        example: "+79991234567"
        type: string
    type: object
  handlers.StartResponse:
    properties:
      whatsapp_link:
        example: https://wa.me/79991234567?text=Мой%20код%20подтверждения%3A%20123456
        type: string
    type: object
  models.Order:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      ownerID:
        type: string
      total:
        type: number
    type: object
  models.Product:
    properties:
      category_id:
        type: integer
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
  services.CartItemResponse:
    properties:
      name:
        type: string
      price:
        type: number
      product_id:
        type: integer
      quantity:
        type: integer
      total:
        type: number
    type: object
info:
  contact: {}
paths:
  /api/admin/categories:
    post:
      consumes:
      - application/json
      description: Добавляет новую категорию (только для администратора)
      parameters:
      - description: Название категории
        in: body
        name: input
        required: true
        schema:
          properties:
            name:
              type: string
          type: object
      produces:
      - text/plain
      responses:
        "201":
          description: Category created
          schema:
            type: string
        "400":
          description: Invalid body or duplicate name
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Создать новую категорию
      tags:
      - Категории
  /api/admin/categories/{id}:
    delete:
      description: Удаляет категорию по ID (только для администратора)
      parameters:
      - description: ID категории
        in: path
        name: id
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: Category deleted
          schema:
            type: string
        "400":
          description: Удаление не удалось
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Удалить категорию
      tags:
      - Категории
    put:
      consumes:
      - application/json
      description: Изменяет название категории (только для администратора)
      parameters:
      - description: ID категории
        in: path
        name: id
        required: true
        type: integer
      - description: Новое имя категории
        in: body
        name: input
        required: true
        schema:
          properties:
            name:
              type: string
          type: object
      produces:
      - text/plain
      responses:
        "200":
          description: Category updated
          schema:
            type: string
        "400":
          description: Invalid input or update failed
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Обновить категорию
      tags:
      - Категории
  /api/admin/orders:
    get:
      description: Возвращает список всех заказов (только для админа)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить все заказы (админ)
      tags:
      - Админ / Заказы
  /api/admin/orders/export:
    get:
      description: Экспортирует все заказы в формате CSV (только для админа)
      produces:
      - text/csv
      responses:
        "200":
          description: CSV файл
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Экспорт заказов в CSV (админ)
      tags:
      - Админ / Заказы
  /api/admin/products:
    post:
      consumes:
      - application/json
      description: Создаёт новый товар (только для администратора)
      parameters:
      - description: Данные товара
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - text/plain
      responses:
        "201":
          description: Product added
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Добавить товар (админ)
      tags:
      - Товар
  /api/admin/products/{id}:
    put:
      consumes:
      - application/json
      description: Обновляет существующий товар по его ID (только для администратора)
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные товара
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - text/plain
      responses:
        "200":
          description: Product updated
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Обновить товар (админ)
      tags:
      - Товар
  /api/cart:
    get:
      description: Возвращает список товаров в корзине для owner_id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.CartItemResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить содержимое корзины
      tags:
      - Корзина
    post:
      consumes:
      - application/json
      description: Добавляет товар в корзину по owner_id (user или ip)
      parameters:
      - description: ID товара и количество
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.AddToCartRequest'
      produces:
      - text/plain
      responses:
        "201":
          description: Added to cart
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Добавить товар в корзину
      tags:
      - Корзина
  /api/cart/{product_id}:
    delete:
      description: Удаляет товар по ID из корзины owner_id
      parameters:
      - description: ID товара
        in: path
        name: product_id
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: Item deleted
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Удалить товар из корзины
      tags:
      - Корзина
    put:
      consumes:
      - application/json
      description: Обновляет количество указанного товара для owner_id
      parameters:
      - description: ID товара
        in: path
        name: product_id
        required: true
        type: integer
      - description: Новое количество
        in: body
        name: input
        required: true
        schema:
          properties:
            quantity:
              type: integer
          type: object
      produces:
      - text/plain
      responses:
        "200":
          description: Quantity updated
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Обновить количество товара в корзине
      tags:
      - Корзина
  /api/cart/clear:
    delete:
      description: Удаляет все товары из корзины owner_id
      produces:
      - text/plain
      responses:
        "200":
          description: Cart cleared
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Очистить корзину
      tags:
      - Корзина
  /api/categories:
    get:
      description: Возвращает все доступные категории товаров
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить список категорий
      tags:
      - Категории
  /api/login:
    post:
      consumes:
      - application/json
      description: Выполняет вход пользователя и возвращает JWT-токен
      parameters:
      - description: Имя пользователя и пароль
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              token:
                type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - Пользователь
  /api/me:
    get:
      description: Возвращает профиль текущего пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              ' role':
                type: string
              ' username':
                type: string
              id:
                type: integer
            type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить информацию о пользователе
      tags:
      - Пользователь
  /api/order:
    post:
      description: Оформляет заказ из текущей корзины owner_id
      produces:
      - text/plain
      responses:
        "200":
          description: Order placed successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Оформить заказ
      tags:
      - Заказ
  /api/orders:
    get:
      description: Возвращает список заказов для текущего owner_id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить заказы пользователя
      tags:
      - Заказ
  /api/products:
    get:
      description: Получает список товаров с возможностью фильтрации
      parameters:
      - description: Поиск по названию
        in: query
        name: search
        type: string
      - description: Фильтр по категории
        in: query
        name: category
        type: string
      - description: Минимальная цена
        in: query
        name: min_price
        type: number
      - description: Максимальная цена
        in: query
        name: max_price
        type: number
      - description: Сортировка
        in: query
        name: sort
        type: string
      - description: Ограничение количества результатов
        in: query
        name: limit
        type: integer
      - description: Сдвиг для пагинации
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить список товаров
      tags:
      - Товар
  /api/products/{id}:
    get:
      description: Возвращает детали товара по его идентификатору
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить товар по ID
      tags:
      - Товар
  /api/register:
    post:
      consumes:
      - application/json
      description: Создаёт нового пользователя
      parameters:
      - description: Имя пользователя и пароль
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterRequest'
      produces:
      - text/plain
      responses:
        "201":
          description: Пользователь успешно зарегистрирован
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Регистрация пользователя
      tags:
      - Пользователь
  /verify/confirm:
    post:
      consumes:
      - application/json
      description: Проверяет код подтверждения, подтверждает номер телефона
      parameters:
      - description: Телефон и код
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.ConfirmRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Phone confirmed
          schema:
            type: string
        "400":
          description: Invalid request or code
          schema:
            type: string
      summary: Подтвердить код
      tags:
      - verification
  /verify/start:
    post:
      consumes:
      - application/json
      description: Генерирует код и возвращает ссылку на WhatsApp с готовым сообщением
      parameters:
      - description: Телефон пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.StartRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.StartResponse'
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Failed to start verification
          schema:
            type: string
      summary: Начать подтверждение телефона
      tags:
      - verification
  /ws/orders:
    get:
      description: Устанавливает WebSocket-соединение. Админы получают уведомления
        о новых заказах.
      produces:
      - application/json
      responses:
        "101":
          description: Switching Protocols
          schema:
            type: string
      summary: Подключение к WebSocket для уведомлений о заказах
      tags:
      - WebSocket
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
